version: "3"
services:
  edge-ml_model:
    image: tecokit/edge-ml_model_beta:latest
    container_name: edge-ml_model
    restart: always
    volumes:
      - .env-docker-local:/app/.env:ro
    build: ./ml
    ports:
      - "3003:3003"
    networks:
      - backbone
    depends_on:
      - s3
      - mongo
  edge-ml_backend:
    container_name: edge-ml_backend
    image: tecokit/edge-ml_backend_beta:latest
    restart: always
    build: ./backend
    volumes:
      - .env-docker-local:/app/.env:ro
    ports:
      - "3001:3001"
    links:
      - mongo
    depends_on: 
      - rabbitmq
    networks:
      - backbone
  edge-ml_authentication:
    container_name: edge-ml_authentication
    image: tecokit/edge-ml_authentication_beta:latest
    restart: always
    build: ./authentication
    volumes:
      - .env-docker-local:/app/.env:ro
    ports:
      - "3002:3002"
    links:
      - mongo
    networks:
      - backbone
  edge-ml_frontend:
    container_name: edge-ml_frontend
    image: tecokit/edge-ml_frontend_beta:latest
    environment:
      - NODE_ENV=production
    build: ./frontend
    restart: always
    links:
     - edge-ml_authentication
     - edge-ml_backend
    depends_on: 
      - edge-ml_backend
      - edge-ml_authentication
      - edge-ml_dataset-store
      - edge-ml_model
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docs:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backbone
  edge-ml_dataset-store:
    container_name: edge-ml_dataset-store
    image: tecokit/edge-ml_dataset-store_beta:latest
    build: ./Dataset-store
    restart: always
    ports:
      - 3004:3004
    volumes:
      - ./tsData:/app/app/DATA
      - ./rawCSVDATA:/app/app/RAW_CSV_DATA
      - .env-docker-local:/app/app/.env:ro
    networks:
      - backbone
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo:4
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      - NETWORK_ACCESS=internal
    networks:
      - backbone
  rabbitmq:
    container_name: 'rabbitmq'
    restart: always
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
      - backbone
  s3:
    container_name: s3
    restart: always
    image: scireum/s3-ninja
    ports:
      - 9444:9000
      - 8081:8080
    volumes:
      - ./s3Data:/home/sirius/data
    networks:
      - backbone
  # arduino-compiler:
  #   container_name: arduino-compiler
  #   build: ./firmwareCompile
  #   restart: always
  #   ports:
  #     - 3005:3005
  #   networks:
  #     - backbone
volumes:
  static-content:
  rabbitmq_data:
  rabbitmq_log:
networks:
  backbone:
    driver: bridge
