version: "3"
services:
  explorer-model:
    container_name: explorer-model
    restart: always
    build: ./ml
    image: tecokit/explorer-model
    ports:
      - "3003:3003"
    networks:
      - backbone
  explorer-backend:
    container_name: explorer-backend
    restart: always
    build: ./backend
    image: tecokit/explorer-backend
    ports:
      - "3001:3001"
    links:
      - mongo
    depends_on: 
      - explorer-authentication
    networks:
      - backbone
  explorer-authentication:
    container_name: explorer-authentication
    restart: always
    build: ./authentication
    image: tecokit/explorer-authentication
    ports:
      - "3002:3002"
    links:
      - mongo
    networks:
      - backbone
  explorer-frontend:
    container_name: explorer-frontend
    build: ./frontend
    environment:
      - NODE_ENV=production
    image: tecokit/explorer-frontend
    restart: always
    links:
     - explorer-authentication
     - explorer-backend
     - explorer-model
     - explorer-firmware-compile
    depends_on: 
      - explorer-backend
      - explorer-authentication
      - explorer-model
      - explorer-firmware-compile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docs:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backbone

  explorer-firmware-compile:
    container_name: explorer-firmware-compile    
    build: ./firmwareCompile
    restart: always
    image: tecokit/explorer-firmware-compile
    ports: 
        - 3004:8000
    networks:
      - backbone  

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      - NETWORK_ACCESS=internal
    networks:
      - backbone
volumes:
  static-content:

networks:
  backbone:
    driver: bridge
