version: "3"
services:
  explorer-model:
    container_name: explorer-model
    restart: always
    build: ./ml
    image: tecokit/explorer-model
    ports:
      - "3003:3003"
    networks:
      - backbone
  explorer-backend:
    container_name: explorer-backend
    restart: always
    build: ./backend
    image: tecokit/explorer-backend
    ports:
      - "3001:3001"
    links:
      - mongo
    depends_on:
      - explorer-authentication
    networks:
      - backbone
  explorer-authentication:
    container_name: explorer-authentication
    restart: always
    build: ./authentication
    image: tecokit/explorer-authentication
    ports:
      - "3002:3002"
    links:
      - mongo
    networks:
      - backbone
  explorer-frontend:
    container_name: explorer-frontend
    build: ./frontend
    environment:
      - NODE_ENV=production
    image: tecokit/explorer-frontend
    restart: always
    links:
      - explorer-authentication
      - explorer-backend
      - explorer-model
    depends_on:
      - explorer-backend
      - explorer-authentication
      - explorer-model
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docs:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backbone
  dataset-store:
    container_name: dataset-store
    build: ./Dataset-store
    restart: always
    ports:
      - 3004:3004
    volumes:
      - ./tsData:/app/app/DATA
      - ./rawCSVDATA:/app/app/RAW_UPLOAD_DATA
    networks:
      - backbone
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      - NETWORK_ACCESS=internal
    networks:
      - backbone
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
      - backbone
volumes:
  static-content:
  rabbitmq_data:
  rabbitmq_log:


networks:
  backbone:
    driver: bridge
