version: "3"
services:
  explorer-backend:
    container_name: explorer-backend
    restart: always
    image: tecokit/explorer-backend
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on: 
      - explorer-authentication
    networks:
      - backbone
  explorer-authentication:
    container_name: explorer-authentication
    restart: always
    image: tecokit/explorer-authentication
    ports:
      - "3002:3002"
    links:
      - mongo
    networks:
      - backbone
  explorer-frontend:
    container_name: explorer-frontend
    environment:
      - NODE_ENV=production
    image: tecokit/explorer-frontend
    restart: always
    links:
     - explorer-authentication
     - explorer-backend
    depends_on: 
      - explorer-backend
      - explorer-authentication
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docs:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backbone
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      - NETWORK_ACCESS=internal
    networks:
      - backbone
volumes:
  static-content:

networks:
  backbone:
    driver: bridge
